# Generated by Django 5.0.7 on 2024-08-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
                ('sede', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=60)),
                ('modalidad', models.CharField(choices=[('liga', 'Liga'), ('eliminacion_directa', 'Eliminacion directa'), ('copa', 'Copa'), ('combinado', 'Liga y eliminación directa'), ('grupos', 'Fase de Grupos y Playoffs'), ('ascenso_y_descenso', 'Ascenso y Descenso')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('abreviacion_nombre', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaGlobalEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_agregados', models.IntegerField()),
                ('tiros_esquina', models.IntegerField()),
                ('tiros_libres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('fecha_debut', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('finalizado', models.BooleanField(default=False)),
                ('escenario', models.CharField(max_length=50)),
                ('duracion_minutos', models.IntegerField()),
                ('amistoso', models.BooleanField(default=False)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1', to='sistema_futbol_app.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2', to='sistema_futbol_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('tipo', models.CharField(choices=[('principal', 'Arbitro Principal'), ('asistente', 'Arbitro Asistente'), ('cuarto', 'Cuarto Arbitro'), ('de_video', 'Arbitro de Video'), ('asistente_de_video', 'Arbitro Asistente de Video')], max_length=50)),
                ('estadistica_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticapartido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaGlobalJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorDeEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(choices=[('portero', 'Portero'), ('lateral', 'Lateral'), ('libero', 'Líbero'), ('defensa_central', 'Defensa Central'), ('centrocampista', 'Centrocampista'), ('delantero', 'Delantero'), ('extremo_izquierdo', 'Extremo Izquierdo'), ('extremo_derecho', 'Extremo Derecho'), ('media_punta', 'Media Punta'), ('falso_nueve', 'Falso Nueve')], max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadistica_global_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticaglobaljugador')),
                ('estadistica_gobal_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticaglobalequipo')),
                ('estadistica_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticapartido')),
                ('jugadorDeEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.jugadordeequipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('estadistica_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticapartido')),
                ('jugador_cometio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_cometio', to='sistema_futbol_app.jugadordeequipo')),
                ('jugador_recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_recibio', to='sistema_futbol_app.jugadordeequipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('estadistica_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticapartido')),
                ('jugador_entra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_entra', to='sistema_futbol_app.jugadordeequipo')),
                ('jugador_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_sale', to='sistema_futbol_app.jugadordeequipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_equipo1', models.IntegerField()),
                ('goles_equipo2', models.IntegerField()),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.partido')),
            ],
        ),
        migrations.AddField(
            model_name='estadisticapartido',
            name='partido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.partido'),
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.campeonato')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='RowTablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=1)),
                ('puntos', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('gc', models.IntegerField(default=0)),
                ('dg', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.equipo')),
                ('tabla_posiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.tablaposiciones')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Amarilla'), ('roja', 'Roja')], max_length=10)),
                ('estadistica_global_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticaglobaljugador')),
                ('estadistica_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.estadisticapartido')),
                ('jugadorDeEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.jugadordeequipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaCampeonatoEquipo',
            fields=[
                ('estadisticaglobalequipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema_futbol_app.estadisticaglobalequipo')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.campeonato')),
            ],
            bases=('sistema_futbol_app.estadisticaglobalequipo',),
        ),
        migrations.CreateModel(
            name='EstadisticaCampeonatoJugador',
            fields=[
                ('estadisticaglobaljugador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema_futbol_app.estadisticaglobaljugador')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.campeonato')),
            ],
            bases=('sistema_futbol_app.estadisticaglobaljugador',),
        ),
        migrations.CreateModel(
            name='PartidoCampeonato',
            fields=[
                ('partido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema_futbol_app.partido')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_futbol_app.campeonato')),
            ],
            bases=('sistema_futbol_app.partido',),
        ),
    ]
