# Generated by Django 5.0.7 on 2024-08-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_futbol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='goles_equipo1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marcador',
            name='goles_equipo2',
            field=models.IntegerField(default=0),
        ),
    ]
