# Generated by Django 5.0.7 on 2024-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_futbol_app', '0002_alter_marcador_goles_equipo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticapartido',
            name='minutos_agregados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticapartido',
            name='tiros_esquina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticapartido',
            name='tiros_libres',
            field=models.IntegerField(default=0),
        ),
    ]
