# Generated by Django 5.0.7 on 2024-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_futbol_app', '0004_alter_estadisticaglobaljugador_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='minuto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='minuto',
            field=models.IntegerField(default=0),
        ),
    ]
