# Generated by Django 5.0.7 on 2024-07-22 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TablaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RowTablaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=100)),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costos_materiales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costos_personal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_generales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco', to='app_libro_registro.subrow')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja', to='app_libro_registro.subrow')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iva', to='app_libro_registro.subrow')),
                ('TablaRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_libro_registro.tablaregistro')),
            ],
        ),
    ]
